# Messy Employee Dataset - Hands On

https://www.kaggle.com/datasets/desolution01/messy-employee-dataset

Columns Included:
- Employee_ID: Unique synthetic ID (e.g., EMP1001)
- First_Name, Last_Name: Randomly generated personal names
- Name: Full name (may be redundant with first/last)
- Age: Includes missing values
- Department_Region: Compound column (e.g., "HR-Florida")
- Status: Employee status (Active, Inactive, Pending)
- Join_Date: Inconsistent format (YYYY/MM/DD)
- Salary: Includes invalid entries (e.g., "N/A")
- Email, Phone: Synthetic contact information
- Performance_Score: Categorical performance rating
- Remote_Work: Boolean flag (True/False)

In [63]:
# import libs and dataset
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('Messy_Employee_dataset.csv')

In [64]:
#check head
df.head()

,Employee_ID,First_Name,Last_Name,Age,Department_Region,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work
0,EMP1000,Bob,Davis,25.0,DevOps-California,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True
1,EMP1001,Bob,Brown,NaN,Finance-Texas,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True
2,EMP1002,Alice,Jones,NaN,Admin-Nevada,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True
3,EMP1003,Eva,Davis,25.0,Admin-Nevada,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True
4,EMP1004,Frank,Williams,25.0,Cloud Tech-Florida,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False

In [65]:
# check info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Department_Region  1020 non-null   object
 5   Status             1020 non-null   object
 6   Join_Date          1020 non-null   object
 7   Salary             996 non-null    float64
 8   Email              1020 non-null   object
 9   Phone              1020 non-null   int64
 10  Performance_Score  1020 non-null   object
 11  Remote_Work        1020 non-null   bool
dtypes: bool(1), float64(2), int64(1), object(8)
memory usage: 88.8+ KB

What did you find by looking at the info? *Write here*

In [66]:
# Check values for each column
for col in df.columns:
    print("=" * 80)
    print(col)
    print(df[col].dropna().unique()[:30])

================================================================================
Employee_ID
['EMP1000' 'EMP1001' 'EMP1002' 'EMP1003' 'EMP1004' 'EMP1005' 'EMP1006'
 'EMP1007' 'EMP1008' 'EMP1009' 'EMP1010' 'EMP1011' 'EMP1012' 'EMP1013'
 'EMP1014' 'EMP1015' 'EMP1016' 'EMP1017' 'EMP1018' 'EMP1019' 'EMP1020'
 'EMP1021' 'EMP1022' 'EMP1023' 'EMP1024' 'EMP1025' 'EMP1026' 'EMP1027'
 'EMP1028' 'EMP1029']
================================================================================
First_Name
['Bob' 'Alice' 'Eva' 'Frank' 'Charlie' 'David' 'Heidi' 'Grace']
================================================================================
Last_Name
['Davis' 'Brown' 'Jones' 'Williams' 'Garcia' 'Johnson' 'Miller' 'Smith']
================================================================================
Age
[25. 40. 30. 35.]
================================================================================
Department_Region
['DevOps-California' 'Finance-Texas' 'Admin-Nevada' 'Cloud Tech-Florida'
 'Sales-Texas' 'DevOps-New York' 'Cloud Tech-New York' 'HR-New York'
 'Finance-California' 'Sales-Florida' 'DevOps-Illinois'
 'Cloud Tech-Nevada' 'Admin-Illinois' 'Cloud Tech-Illinois'
 'Sales-Illinois' 'Finance-Nevada' 'Admin-Texas' 'Sales-New York'
 'Finance-Florida' 'Admin-California' 'HR-Texas' 'HR-California'
 'HR-Nevada' 'Cloud Tech-Texas' 'Sales-California' 'HR-Illinois'
 'Admin-New York' 'Admin-Florida' 'HR-Florida' 'Sales-Nevada']
================================================================================
Status
['Active' 'Pending' 'Inactive']
================================================================================
Join_Date
['4/2/2021' '7/10/2020' '12/7/2023' '11/27/2021' '1/5/2022' '6/10/2020'
 '4/3/2020' '7/17/2022' '12/8/2023' '8/4/2022' '7/6/2024' '9/4/2023'
 '3/5/2024' '10/10/2020' '6/10/2024' '5/29/2021' '4/23/2024' '11/28/2024'
 '9/19/2024' '1/2/2020' '5/8/2021' '9/19/2020' '3/9/2021' '2/3/2022'
 '2/13/2020' '4/30/2020' '10/2/2023' '7/12/2020' '10/11/2023' '5/24/2021']
================================================================================
Salary
[ 59767.65  65304.66  88145.9   69450.99 109324.61  88642.84  96288.43
  94497.91 115565.82  76561.88  72081.71  84946.19  89295.77  85666.84
  97633.68 117975.49  94867.33 100377.65  94726.46  91926.12 111460.67
  96182.56 115023.94  80667.01  91181.61  66025.92  83979.01  56785.16
  95741.88  63411.31]
================================================================================
Email
['bob.davis@example.com' 'bob.brown@example.com' 'alice.jones@example.com'
 'eva.davis@example.com' 'frank.williams@example.com'
 'alice.garcia@example.com' 'frank.jones@example.com'
 'bob.jones@example.com' 'frank.davis@example.com'
 'charlie.johnson@example.com' 'david.williams@example.com'
 'david.davis@example.com' 'heidi.williams@example.com'
 'grace.williams@example.com' 'grace.jones@example.com'
 'alice.brown@example.com' 'grace.garcia@example.com'
 'charlie.garcia@example.com' 'charlie.williams@example.com'
 'bob.miller@example.com' 'david.garcia@example.com'
 'david.miller@example.com' 'frank.miller@example.com'
 'heidi.johnson@example.com' 'charlie.jones@example.com'
 'bob.smith@example.com' 'charlie.brown@example.com'
 'grace.johnson@example.com' 'heidi.miller@example.com'
 'grace.smith@example.com']
================================================================================
Phone
[-1651623197 -1898471390 -5596363211 -3476490784 -1586734256 -5409003485
 -4518376063 -4134327559 -4177656123 -8156985699 -2720634590 -1238296576
 -2429543164 -2669300892 -1734206968 -4215291085 -7713334475 -2639343625
 -2044397358 -7107256365 -9411800536 -5990048963 -6528092427 -7572158623
 -1502745643 -9485625727 -7032032073 -2761707586 -7712151341 -2849939088]
================================================================================
Performance_Score
['Average' 'Excellent' 'Good' 'Poor']
================================================================================
Remote_Work
[ True False]

What did this tell you? *Write here*

How to best approach cleaning? *Write here or make table*

## Clean each column

We will separate the cleaning by column - sometimes it is easier to analyse that way. 

In some, we will give you the guidelines to treat it. In some, you will have to think based on the previous class exercise (and do it, as needed).

In [90]:
# Check and clean duplicated by Employee ID
df = df.drop_duplicates(subset="Employee_ID", keep="first")

In [68]:
# Employee ID

In [69]:
# First_Name

In [70]:
# Last_Name

In [71]:
# Department_Region
# Two informations in one column - separate into two columns, remove the original column and analyse again it other treatment is needed

df['Department'] = df['Department_Region'].str.split('-').str[0]
df['Region'] = df['Department_Region'].str.split('-').str[1]

df.drop(["Department_Region"], inplace=True, axis=1)
df.head()

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
0,EMP1000,Bob,Davis,25.0,Active,4/2/2021,59767.65,bob.davis@example.com,-1651623197,Average,True,DevOps,California
1,EMP1001,Bob,Brown,NaN,Active,7/10/2020,65304.66,bob.brown@example.com,-1898471390,Excellent,True,Finance,Texas
2,EMP1002,Alice,Jones,NaN,Pending,12/7/2023,88145.90,alice.jones@example.com,-5596363211,Good,True,Admin,Nevada
3,EMP1003,Eva,Davis,25.0,Inactive,11/27/2021,69450.99,eva.davis@example.com,-3476490784,Good,True,Admin,Nevada
4,EMP1004,Frank,Williams,25.0,Active,1/5/2022,109324.61,frank.williams@example.com,-1586734256,Poor,False,Cloud Tech,Florida

In [72]:
# Status

In [73]:
# Email

In [74]:
# Join_Date
df['Join_Date'] = pd.to_datetime(df['Join_Date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                809 non-null    float64
 4   Status             1020 non-null   object
 5   Join_Date          1020 non-null   datetime64[ns]
 6   Salary             996 non-null    float64
 7   Email              1020 non-null   object
 8   Phone              1020 non-null   int64
 9   Performance_Score  1020 non-null   object
 10  Remote_Work        1020 non-null   bool
 11  Department         1020 non-null   object
 12  Region             1020 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(2), int64(1), object(8)
memory usage: 96.7+ KB

In [75]:
# Phone
# Remove "-" before phone number
df['Phone'] = df['Phone'].astype(str).str.replace("-","",regex=False)

In [76]:
# Performance_Score

In [77]:
# Age
# Treat null values - think about how it's best to do so
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [78]:
# Salary
# Treat null values - think about how it's best to do so
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        1020 non-null   object
 1   First_Name         1020 non-null   object
 2   Last_Name          1020 non-null   object
 3   Age                1020 non-null   float64
 4   Status             1020 non-null   object
 5   Join_Date          1020 non-null   datetime64[ns]
 6   Salary             1020 non-null   float64
 7   Email              1020 non-null   object
 8   Phone              1020 non-null   object
 9   Performance_Score  1020 non-null   object
 10  Remote_Work        1020 non-null   bool
 11  Department         1020 non-null   object
 12  Region             1020 non-null   object
dtypes: bool(1), datetime64[ns](1), float64(2), object(9)
memory usage: 96.7+ KB

## Check Inconsistencies based on business rules on the following table

| Column    | Business rule                                                                              | Example of invalid value                                         |
| --------- | ------------------------------------------------------------------------------------------ | ---------------------------------------------------------------- |
| Email     | Must follow the pattern `first_name.last_name@example.com`                                 | `john@example.com`, `john.smith@gmail.com`, `jsmith@example.com` |
| Salary    | Must be within the accepted company salary range, for example between `52000` and `200000` | `5000`, `999999`, negative values                                |
| Age       | Must be within a realistic working-age range, for example between `18` and `70`            | `12`, `95`, negative values                                      |
| Join Date | Must be before today and after `2019`, the company foundation year                         | future dates, `2018-05-10`                                       |

In [80]:
# Check and correct if needed

In [81]:
today = pd.Timestamp.today().normalize()

In [82]:
# 1. Email must be first_name.last_name@example.com

invalid_email = df[
    df["Email"] != (
        df["First_Name"].str.lower() + "." + df["Last_Name"].str.lower() + "@example.com"
    )
]

invalid_email

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work, Department, Region]
Index: []

In [83]:
# 2. Salary must be within the accepted range

invalid_salary = df[
    ~df["Salary"].between(52000, 200000)
]

invalid_salary

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region
77,EMP1077,Grace,Brown,30.000000,Pending,2022-12-29,51887.65,grace.brown@example.com,6110627370,Good,False,Finance,New York
130,EMP1130,Frank,Brown,25.000000,Pending,2022-07-24,51074.33,frank.brown@example.com,7303379336,Excellent,True,Finance,Texas
184,EMP1184,Frank,Smith,25.000000,Active,2022-06-12,51311.91,frank.smith@example.com,864035532,Excellent,False,Finance,Nevada
218,EMP1218,Heidi,Garcia,25.000000,Pending,2023-01-02,51150.47,heidi.garcia@example.com,1159319524,Excellent,False,Cloud Tech,Florida
268,EMP1268,Grace,Davis,32.484549,Pending,2023-07-12,51865.30,grace.davis@example.com,305690673,Poor,True,HR,Nevada
299,EMP1299,Alice,Garcia,32.484549,Inactive,2024-01-21,51523.93,alice.garcia@example.com,18418619,Average,True,Finance,Nevada
390,EMP1390,Eva,Williams,35.000000,Inactive,2023-04-06,50173.12,eva.williams@example.com,7637153987,Poor,False,Finance,Florida
394,EMP1394,Heidi,Williams,25.000000,Inactive,2022-07-23,50047.32,heidi.williams@example.com,2407875417,Good,False,Cloud Tech,New York
415,EMP1415,Charlie,Smith,25.000000,Active,2023-12-07,50794.54,charlie.smith@example.com,425488213,Good,True,Cloud Tech,Nevada
424,EMP1424,Eva,Garcia,35.000000,Pending,2022-07-24,50557.84,eva.garcia@example.com,104159148,Average,True,HR,Texas
426,EMP1426,David,Smith,32.484549,Active,2022-04-19,51673.72,david.smith@example.com,8723244078,Poor,False,Admin,New York
454,EMP1454,Charlie,Jones,35.000000,Inactive,2020-05-01,51533.90,charlie.jones@example.com,3896086,Poor,True,DevOps,New York
465,EMP1465,David,Davis,30.000000,Active,2021-08-26,51405.46,david.davis@example.com,4967066702,Average,True,Finance,Texas
516,EMP1516,Alice,Garcia,35.000000,Active,2023-10-17,50288.67,alice.garcia@example.com,61558107,Excellent,False,Sales,New York
524,EMP1524,Heidi,Johnson,30.000000,Pending,2023-07-14,50651.32,heidi.johnson@example.com,3684748835,Poor,False,Admin,Nevada
549,EMP1549,Frank,Davis,40.000000,Pending,2021-03-30,50153.79,frank.davis@example.com,3758309450,Good,True,Cloud Tech,Texas
643,EMP1643,David,Smith,35.000000,Pending,2023-01-02,50680.62,david.smith@example.com,6065274032,Average,True,Finance,California
691,EMP1691,David,Miller,25.000000,Inactive,2021-10-26,51054.74,david.miller@example.com,3991062271,Excellent,False,Admin,Nevada
751,EMP1751,Eva,Jones,30.000000,Active,2021-01-13,51833.88,eva.jones@example.com,771130620,Average,True,Admin,Texas
782,EMP1782,Charlie,Garcia,32.484549,Inactive,2021-01-31,50110.66,charlie.garcia@example.com,904637659,Average,True,Admin,Nevada
820,EMP1820,Eva,Davis,40.000000,Active,2023-04-08,50568.35,eva.davis@example.com,2218231554,Good,True,DevOps,California
848,EMP1848,Frank,Davis,30.000000,Active,2023-10-09,50593.33,frank.davis@example.com,1880819047,Excellent,True,HR,Illinois
858,EMP1858,Heidi,Johnson,25.000000,Pending,2023-08-04,50060.73,heidi.johnson@example.com,3176539704,Poor,False,Finance,New York
898,EMP1898,Heidi,Davis,40.000000,Pending,2024-03-22,50869.61,heidi.davis@example.com,7269608436,Average,True,Admin,Texas
922,EMP1922,Grace,Smith,40.000000,Inactive,2020-11-15,50300.60,grace.smith@example.com,1945887070,Good,False,Admin,Florida
938,EMP1938,Grace,Miller,30.000000,Pending,2021-05-16,51990.98,grace.miller@example.com,5143776935,Excellent,True,Finance,Nevada
996,EMP1996,David,Smith,40.000000,Active,2021-01-28,51939.29,david.smith@example.com,2442607818,Excellent,True,Admin,Texas
1014,EMP2014,Grace,Jones,30.000000,Pending,2021-05-16,51990.98,grace.jones@example.com,2470739200,Excellent,True,Finance,Nevada

They need to get a raise, per minimum salary of the company. Maybe we could do a flag and report to the business

In [84]:
minimum_salary = 52000

df.loc[df["Salary"] < minimum_salary, "New_Salary"] = minimum_salary

df.loc[df["Salary"] < minimum_salary, "Raise"] = (
    df["New_Salary"] - df["Salary"]
)

# Data to send to the HR
df.loc[df["Salary"] < minimum_salary, ["Employee_ID", "Raise"]]

     Employee_ID    Raise
77       EMP1077   112.35
130      EMP1130   925.67
184      EMP1184   688.09
218      EMP1218   849.53
268      EMP1268   134.70
299      EMP1299   476.07
390      EMP1390  1826.88
394      EMP1394  1952.68
415      EMP1415  1205.46
424      EMP1424  1442.16
426      EMP1426   326.28
454      EMP1454   466.10
465      EMP1465   594.54
516      EMP1516  1711.33
524      EMP1524  1348.68
549      EMP1549  1846.21
643      EMP1643  1319.38
691      EMP1691   945.26
751      EMP1751   166.12
782      EMP1782  1889.34
820      EMP1820  1431.65
848      EMP1848  1406.67
858      EMP1858  1939.27
898      EMP1898  1130.39
922      EMP1922  1699.40
938      EMP1938     9.02
996      EMP1996    60.71
1014     EMP2014     9.02

In [85]:
# 3. Age must be within the accepted range

invalid_age = df[
    ~df["Age"].between(18, 70)
]

invalid_age

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work, Department, Region, New_Salary, Raise]
Index: []

In [86]:
# 4. Join Date must be after 2019 and before today

invalid_join_date = df[
    ~df["Join_Date"].between(
        pd.Timestamp("2019-01-01"),
        today,
        inclusive="both"
    )
]

invalid_join_date

Empty DataFrame
Columns: [Employee_ID, First_Name, Last_Name, Age, Status, Join_Date, Salary, Email, Phone, Performance_Score, Remote_Work, Department, Region, New_Salary, Raise]
Index: []

## Extract and create new column

In [87]:
# Make a column for company time, based on todays date and join date
df["Company_Time"] = (
    today - pd.to_datetime(df["Join_Date"], errors="coerce")
).dt.days

In [88]:
df

,Employee_ID,First_Name,Last_Name,Age,Status,Join_Date,Salary,Email,Phone,Performance_Score,Remote_Work,Department,Region,New_Salary,Raise,Company_Time
0,EMP1000,Bob,Davis,25.000000,Active,2021-04-02,59767.650000,bob.davis@example.com,1651623197,Average,True,DevOps,California,NaN,NaN,1887
1,EMP1001,Bob,Brown,32.484549,Active,2020-07-10,65304.660000,bob.brown@example.com,1898471390,Excellent,True,Finance,Texas,NaN,NaN,2153
2,EMP1002,Alice,Jones,32.484549,Pending,2023-12-07,88145.900000,alice.jones@example.com,5596363211,Good,True,Admin,Nevada,NaN,NaN,908
3,EMP1003,Eva,Davis,25.000000,Inactive,2021-11-27,69450.990000,eva.davis@example.com,3476490784,Good,True,Admin,Nevada,NaN,NaN,1648
4,EMP1004,Frank,Williams,25.000000,Active,2022-01-05,109324.610000,frank.williams@example.com,1586734256,Poor,False,Cloud Tech,Florida,NaN,NaN,1609
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,EMP2015,David,Miller,30.000000,Active,2023-08-19,85155.056396,david.miller@example.com,3546212759,Good,True,HR,California,NaN,NaN,1018
1016,EMP2016,David,Johnson,30.000000,Inactive,2021-11-07,100215.060000,david.johnson@example.com,2508261122,Good,True,Cloud Tech,Texas,NaN,NaN,1668
1017,EMP2017,Charlie,Williams,40.000000,Active,2023-10-04,114587.110000,charlie.williams@example.com,1261632487,Average,False,Finance,New York,NaN,NaN,972
1018,EMP2018,Alice,Garcia,30.000000,Inactive,2024-12-16,71318.790000,alice.garcia@example.com,8995729892,Good,True,HR,Florida,NaN,NaN,533
1019,EMP2019,Heidi,Jones,30.000000,Pending,2021-02-22,77764.240000,heidi.jones@example.com,7629745492,Average,False,DevOps,Illinois,NaN,NaN,1926